if vendor/redis-compiled*tar.gz exists then unpack that; else build from source

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -11,7 +11,8 @@ redis_dependency=$(cat $buildpack_dir/buildpack.toml | yj -t | jq -r --arg versi
 [[ "$redis_dependency" == "X" ]] && { echo "     ERROR: Unknown \$REDIS_MAJOR_VERSION"; exit 1; }
 redis_version=$(echo "$redis_dependency" | jq -r ".version")
 redis_src_url=$(echo "$redis_dependency" | jq -r ".source")
-redis_src_sha256=$(echo "$redis_dependency" | jq -r ".source_sha256")
+redis_src_sha256=$(echo "$redis_dependency" | jq -r '.source_sha256')
+redis_compiled_sha256=$(echo "$redis_dependency" | jq -r '.sha256 // "X"')
 
 echo "---> Redis Buildpack"
 mkdir -p $layer_dir
@@ -23,30 +24,35 @@ if [[ "${layer_redis_version:-X}" == "$redis_version" ]] ; then
 else
 (
   echo "---> Install Redis $redis_version"
+  redis_compiled_tgz=$buildpack_dir/vendor/redis-compiled-$redis_version.tar.gz
+  if [[ -f ${redis_compiled_tgz} ]]; then
+    echo "$redis_compiled_sha256  $redis_compiled_tgz" | sha256sum -c --ignore-missing || rm -f $redis_compiled_tgz
+    ( cd $layer_dir; tar xfz $redis_compiled_tgz )
+  else
+    redis_src_tgz=$buildpack_dir/vendor/redis-$redis_version.tar.gz
+    echo "$redis_src_sha256  $redis_src_tgz" | sha256sum -c --ignore-missing || rm -f $redis_src_tgz
+    if [[ ! -f $redis_src_tgz ]]; then
+    (
+      echo "     Downloading Redis $redis_version"
+      rm -rf $redis_src_tgz
+      mkdir -p $buildpack_dir/vendor
+      cd $buildpack_dir/vendor
+      curl -L -o $redis_src_tgz $redis_src_url
+      echo "$redis_src_sha256  $redis_src_tgz" | sha256sum -c
+    )
+    fi
 
-  redis_tgz=$buildpack_dir/vendor/redis-$redis_version.tar.gz
-  echo "$redis_src_sha256  $redis_tgz" | sha256sum -c --ignore-missing || rm -f $redis_tgz
-  if [[ ! -f $redis_tgz ]]; then
-  (
-    echo "     Downloading Redis $redis_version"
-    rm -rf $redis_tgz
-    mkdir -p $buildpack_dir/vendor
-    cd $buildpack_dir/vendor
-    curl -L -o redis-$redis_version.tar.gz $redis_src_url
-    echo "$redis_src_sha256  $redis_tgz" | sha256sum -c
-  )
+    redis_src_dir=$(mktemp -d)
+    function atexit {
+      rm -rf $redis_src_dir
+    }
+    trap atexit EXIT
+    cd $redis_src_dir
+    tar xfz $redis_src_tgz
+    cd redis*/
+
+    mkdir -p $layer_dir/redis
+    make PREFIX=$layer_dir/redis install
   fi
-
-  redis_src_dir=$(mktemp -d)
-  function atexit {
-    rm -rf $redis_src_dir
-  }
-  trap atexit EXIT
-  cd $redis_src_dir
-  tar xfz $redis_tgz
-  cd redis*/
-
-  mkdir -p $layer_dir/redis
-  make PREFIX=$layer_dir/redis install
 )
 fi
